language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install .
script:
  - nosetests --with-coverage --cover-package=evopy --cover-html --cover-branches --cover-erase
  - codecov
  - pylint evopy
  - pylint test
